empleados/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.listar_empleados, name='home'),
    path('empleados/', views.listar_empleados, name='empleados_list'),
    path('empleados-new/', views.agregar_empleado, name='empleados_new'),
    path('empleados-edit/<id_emp>/', views.edit_empleado, name='empleados_edit'),
    path('empleados-delete/<id_emp>/', views.eliminar_empleado, name='empleado_delete'),

    path('proveedores/', views.listar_proveedores, name='proveedores_list'),
    path('proveedores-new/', views.agregar_proveedor, name='proveedores_new'),
    path('proveedores-edit/<id_pro>/', views.edit_proveedor, name='proveedores_edit'),
    path('proveedores-delete/<id_pro>/', views.eliminar_proveedor, name='proveedores_delete'),

    path('productos/', views.listar_productos, name='productos_list'),
    path('productos-new/', views.agregar_producto, name='productos_new'),
    path('productos-edit/<codigo>/', views.edit_producto, name='productos_edit'),
    path('productos-delete/<id>/', views.eliminar_producto, name='productos_delete'),
]

entrega2/urls.py
from . import views
from django.urls import path

urlpatterns = [
    # Rutas de Empleados
    path('empleadosC-list/', views.EmpleadoListView.as_view(), name="empleadosC_list"),
    path('empleadosC-new/', views.EmpleadoCreateView.as_view(), name="empleadosC_new"),
    path('empleadosC-update/<pk>', views.EmpleadoUpdateView.as_view(), name="empleadosC_update"),
    path('empleadosC-delete/<pk>', views.EmpleadoDeleteView.as_view(), name="empleadosC_delete"),

    # Rutas de Proveedores
    path('proveedoresC-list/', views.ProveedorListView.as_view(), name="proveedoresC_list"),
    path('proveedoresC-new/', views.ProveedorCreateView.as_view(), name="proveedoresC_new"),
    path('proveedoresC-update/<pk>', views.ProveedorUpdateView.as_view(), name="proveedoresC_update"),
    path('proveedoresC-delete/<pk>', views.ProveedorDeleteView.as_view(), name="proveedoresC_delete"),

    # Rutas de Productos
    path('productosC-list/', views.ProductoListView.as_view(), name="productosC_list"),
    path('productosC-new/', views.ProductoCreateView.as_view(), name="productosC_new"),
    path('productosC-update/<pk>', views.ProductoUpdateView.as_view(), name="productosC_update"),
    path('productosC-delete/<pk>', views.ProductoDeleteView.as_view(), name="productosC_delete"),
]

the_chaman_king/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('empleados.urls')),
    path('empleados/', include(('empleados.urls', 'empleados'), namespace='empleados')),
    path('proveedores/', include(('empleados.urls', 'empleados'), namespace='proveedores')),
    path('productos/', include(('empleados.urls', 'empleados'), namespace='productos')),

    path('', include('entrega2.urls')),
    path('entrega2/', include(('entrega2.urls', 'entrega2'), namespace='entrega2'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/productos.css' %}" />
    <link rel="icon" type="image/jpg" href="{% static 'img/Logo.png' %}"/>
    <title>Base</title>
</head>

<body>
<header>
    <div class="top-bar">
        <div class="logo">
            <img src="{% static 'img/LogoLargo-ParaFondoOscuro.png' %}" alt="Logo de la empresa">
        </div>
        <div class="search-bar">
            <input type="text" id="search-input" placeholder="Buscar Empleados">
            <button id="search-button">
                <ion-icon name="search-outline"></ion-icon>
            </button>
        </div>
        <div class="user-session">
            <a id="login-button" href="login.html">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24" fill="none"
                     stroke="#000000" stroke-width="1" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M10 3H6a2 2 0 0 0-2 2v14c0 1.1.9 2 2 2h4M16 17l5-5-5-5M19.8 12H9"/>
                </svg>
                Cerrar sesión
            </a>
            <a href="{% url 'empleadosC_list' %}">
                Clases
            </a>
        </div>
    </div>

    <nav class="nav-bar">
        <a href="compras.html">
            <ion-icon name="cart-outline"></ion-icon>
            Compras
        </a>
        <a href="ventas.html">
            <ion-icon name="pricetags-outline"></ion-icon>
            Ventas
        </a>
        <a href="{% url 'empleados:empleados_list' %}">
            <ion-icon name="people-outline"></ion-icon>
            Empleados
        </a>
        <a href="{% url 'proveedores_list' %}">
            <ion-icon name="briefcase-outline"></ion-icon>
            Proveedores
        </a>
        <a href="{% url 'productos_list' %}">
            <ion-icon name="cart-outline"></ion-icon>
            Productos
        </a>
    </nav>
</header>

{% block content %}

{% endblock %}

<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

{% if messages %}
    {% for m in messages %}
        <script>
            Swal.fire({
                'title': 'Felicitaciones',
                'text': '{{ m }}',
                'icon': 'success'
            })
        </script>
    {% endfor %}
{% endif %}

{% block javascript %}

{% endblock %}
</body>

</html>

templates/base/baseC.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/productos.css' %}" />
    <link rel="icon" type="image/jpg" href="{% static 'img/Logo.png' %}"/>
    <title>Base</title>
</head>

<body>
<header>
    <div class="top-bar">
        <div class="logo">
            <img src="{% static 'img/LogoLargo-ParaFondoOscuro.png' %}" alt="Logo de la empresa">
        </div>
        <div class="search-bar">
            <input type="text" id="search-input" placeholder="Buscar Empleados">
            <button id="search-button">
                <ion-icon name="search-outline"></ion-icon>
            </button>
        </div>
        <div class="user-session">
            <a id="login-button" href="login.html">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24" fill="none"
                     stroke="#000000" stroke-width="1" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M10 3H6a2 2 0 0 0-2 2v14c0 1.1.9 2 2 2h4M16 17l5-5-5-5M19.8 12H9"/>
                </svg>
                Cerrar sesión
            </a>
            <a href="{% url 'empleados_list' %}">
                Funciones
            </a>
        </div>
    </div>

    <nav class="nav-bar">
        <a href="#">
            <ion-icon name="cart-outline"></ion-icon>
            Compras
        </a>
        <a href="#">
            <ion-icon name="pricetags-outline"></ion-icon>
            Ventas
        </a>
        <a href="{% url 'empleadosC_list' %}">
            <ion-icon name="people-outline"></ion-icon>
            Empleados
        </a>
        <a href="{% url 'proveedoresC_list' %}">
            <ion-icon name="briefcase-outline"></ion-icon>
            Proveedores
        </a>
        <a href="{% url 'productosC_list' %}">
            <ion-icon name="cart-outline"></ion-icon>
            Productos
        </a>
    </nav>
</header>

{% block content %}

{% endblock %}

<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

{% if messages %}
    {% for m in messages %}
        <script>
            Swal.fire({
                'title': 'Felicitaciones',
                'text': '{{ m }}',
                'icon': 'success'
            })
        </script>
    {% endfor %}
{% endif %}

{% block javascript %}

{% endblock %}
</body>

</html>

templates/base/base_agregar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/agregar.css' %}"/>
    <title>Agregar Empleados</title>
</head>
<body>

{% block content %}

{% endblock %}

<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

{% if messages %}
    {% for m in messages %}
        <script>
            Swal.fire({
                'title': 'Acción realizada',
                'text': '{{ m }}',
                'icon': 'success'
            })
        </script>
    {% endfor %}
{% endif %}

{% block javascript %}

{% endblock %}

</body>
</html>